all: quickSort mergeSort selectionSort insertionSort bubbleSort

bubbleSort: bubbleSort.cpp
	g++ -o bin/bubbleSort bubbleSort.cpp

insertionSort: insertionSort.cpp
	g++ -o bin/insertionSort insertionSort.cpp

quickSort: quickSort.cpp
	g++ -o bin/quickSort quickSort.cpp

mergeSort: mergeSort.cpp
	g++ -o bin/mergeSort mergeSort.cpp

selectionSort: selectionSort.cpp
	g++ -o bin/selectionSort selectionSort.cpp

clean:
	rm -fr bin/* *.o
