all: quickSort mergeSort selectionSort

quickSort: quickSort.cpp
	g++ -o bin/quickSort quickSort.cpp

mergeSort: mergeSort.cpp
	g++ -o bin/mergeSort mergeSort.cpp

selectionSort: selectionSort.cpp
	g++ -o bin/selectionSort selectionSort.cpp

clean:
	rm -fr bin/* selectionSort *.o
